"""init

Revision ID: 23778f5e8c8
Revises: None
Create Date: 2015-12-06 17:57:12.597009

"""

# revision identifiers, used by Alembic.
revision = '23778f5e8c8'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('gamer_dynamics', sa.String(length=16384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_title'), 'game', ['title'], unique=True)
    op.create_table('option',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('together', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('clazz', sa.String(16), nullable=True),
    sa.Column('options', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('game_to_stage',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'stage_id')
    )
    op.create_table('game_trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_id', sa.String(length=16), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('size_of_room', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('opened', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('started', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('string_id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_trial_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['game_trial_id'], ['game_trial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_trial_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('variables', postgresql.HSTORE(), nullable=True),
    sa.Column('show_results', sa.Boolean(), nullable=True),
    sa.Column('show_results', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_trial_id'], ['game_trial.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamer_variables'), 'gamer', ['variables'], unique=False)
    op.create_table('gamer_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamer_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamer.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamer_action_gamer_id'), 'gamer_action', ['gamer_id'], unique=False)
    op.create_index(op.f('ix_gamer_action_room_id'), 'gamer_action', ['room_id'], unique=False)
    op.create_index(op.f('ix_gamer_action_round'), 'gamer_action', ['round'], unique=False)
    op.create_index(op.f('ix_gamer_action_stage_id'), 'gamer_action', ['stage_id'], unique=False)
    op.create_table('history_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('gamer_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('variables', postgresql.HSTORE(), nullable=True),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamer.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_variables_gamer_id'), 'history_variables', ['gamer_id'], unique=False)
    op.create_index(op.f('ix_history_variables_room_id'), 'history_variables', ['room_id'], unique=False)
    op.create_index(op.f('ix_history_variables_round'), 'history_variables', ['round'], unique=False)
    op.create_index(op.f('ix_history_variables_variables'), 'history_variables', ['variables'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_variables_variables'), table_name='history_variables')
    op.drop_index(op.f('ix_history_variables_round'), table_name='history_variables')
    op.drop_index(op.f('ix_history_variables_room_id'), table_name='history_variables')
    op.drop_index(op.f('ix_history_variables_gamer_id'), table_name='history_variables')
    op.drop_table('history_variables')
    op.drop_index(op.f('ix_gamer_action_stage_id'), table_name='gamer_action')
    op.drop_index(op.f('ix_gamer_action_round'), table_name='gamer_action')
    op.drop_index(op.f('ix_gamer_action_room_id'), table_name='gamer_action')
    op.drop_index(op.f('ix_gamer_action_gamer_id'), table_name='gamer_action')
    op.drop_table('gamer_action')
    op.drop_index(op.f('ix_gamer_variables'), table_name='gamer')
    op.drop_table('gamer')
    op.drop_table('room')
    op.drop_table('roles_users')
    op.drop_table('game_trial')
    op.drop_table('game_to_stage')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('stage')
    op.drop_table('role')
    op.drop_table('option')
    op.drop_index(op.f('ix_game_title'), table_name='game')
    op.drop_table('game')
    ### end Alembic commands ###
