"""empty message

Revision ID: ed2b9c022207
Revises: 23778f5e8c8
Create Date: 2016-02-28 21:55:38.696385

"""

# revision identifiers, used by Alembic.
revision = 'ed2b9c022207'
down_revision = '23778f5e8c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamer', sa.Column('shown_results', sa.Boolean(), nullable=True))
    op.drop_column('stage', 'is_public')
    op.drop_column('stage', 'together')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('together', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('stage', sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('gamer', 'shown_results')
    ### end Alembic commands ###
